import type { Metadata } from "next";
import { Navbar } from "@/components";
import { Providers } from "@/components";
import { Geist, Geist_Mono } from "next/font/google";
import { getCategories } from "@/actions/category-actions";
import { getProducts } from "@/actions/product-actions";
import { CategoryTabs } from "@/components/website/products/CategoryTabs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();
  const products = await getProducts();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          <div className="sticky top-0 z-10 bg-white shadow-sm">
            <CategoryTabs categories={categories} totalProducts={products.length} />
          </div>
          <main className="container mx-auto px-4 py-8">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
